apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: quarkus-s2i
images:
- name: quarkus-helloworld
  newName: devrht/quarkus-helloworld
  newTag: latest
