# This is a basic workflow to help you get started with Actions

name: CI

env:
  IMAGE_NAME: quarkus-helloworld
  TAGS: latest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - run: mvn package
      
      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          base-image: docker.io/fabric8/java-alpine-openjdk11-jre
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          content: |
            target/quarkus-hello-world-quarkus-1.0.2-SNAPSHOT-runner.jar
          entrypoint: java -jar quarkus-hello-world-quarkus-1.0.2-SNAPSHOT-runner.jar
          port: 8080
          
       # Setup and Build
      - name: Setup and Build
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: '.'
          # Builder image for a java project
          builder_image: 'registry.access.redhat.com/openjdk/openjdk-11-rhel7'
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}

      # Push Image to Docker registry
      - name: Push To Docker Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}     
          registry: docker.io/tedwidge
          username: tedwidge
          password: 84c304d7-9f44-4d1a-9570-f2e892d61bf4
          #username: ${{ secrets.DOCKER_USERNAME }}
          #password: ${{ secrets.DOCKER_PASSWORD }}
